// acts as controller and service - just less code to write and there is less being passed around - nothing is user facing and all cleaned and generated by other services 
// theres a level of trust im relying on that services will pass correct info - everything is internal and failry standardised so should be fine
// these functions should be low error producing 
import { type EventPayload } from "@services/eventbus";
import { ProfileModelInstance } from "../../models";

export default async function HandleUserCreated(message: EventPayload): Promise<void> {
    // just create a profile with the information
    try {
        const { id, name, email } = message!.message;
        if (!id || !name || !email) {
            throw new Error("Missing required fields in message"); // could potentiall switch the error handling to be more value based rather than throwing errors
        }
        await ProfileModelInstance.create({
            userId: id,
            name,
            email,
        })
        return;
    } catch (err) {
        throw new Error("Error handling USER_CREATED event: ", { cause: err });
    }
}