-- Table is like this because all tables below domains relies on it and will cause problems if not created first
CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN () RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
CREATE TABLE IF NOT EXISTS DOMAINS(
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    NAME VARCHAR(255) NOT NULL,
    OWNER_ID UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ NULL DEFAULT NULL
);
CREATE OR REPLACE TRIGGER update_domains_updated_at BEFORE
UPDATE ON domains FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TABLE IF NOT EXISTS USER_DOMAINS(
    -- join table for users and domains
    USER_ID UUID NOT NULL,
    -- user id not profile id
    DOMAIN_ID UUID NOT NULL REFERENCES domains(id) ON DELETE NO ACTION,
    -- CANT BE DELETED ANYWAY SINCE WE ONLY SOFT DELETE
    -- in the same db so can be 
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ NULL DEFAULT NULL,
    PRIMARY KEY (USER_ID, DOMAIN_ID) -- COMPOSITE KEY SO USER CAN ONLY BE IN DOMAIN ONCE
);
CREATE OR REPLACE TRIGGER update_user_domains_updated_at BEFORE
UPDATE ON user_domains FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE INDEX IF NOT EXISTS IDX_USER_DOMAINS_DOMAIN_ID ON USER_DOMAINS (DOMAIN_ID)
WHERE DELETED_AT IS NULL;
CREATE TABLE IF NOT EXISTS USER_ROLES(
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    USER_ID UUID NOT NULL,
    DOMAIN_ID UUID NOT NULL REFERENCES domains(id) ON DELETE NO ACTION,
    ROLE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ NULL DEFAULT NULL
);
CREATE OR REPLACE TRIGGER update_user_role_updated_at BEFORE
UPDATE ON user_role FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE UNIQUE INDEX IF NOT EXISTS IDX_USER_ROLE_USER_DOMAIN ON USER_ROLE (USER_ID, DOMAIN_ID)
WHERE DELETED_AT IS NULL;