CREATE TABLE IF NOT EXISTS PROFILES(
    ID UUID PRIMARY KEY DEFAULT UUIDV7 (),
    USER_ID UUID NOT NULL,
    -- THIS IS THE USER ID THE PROFILE BELONGS TO  - TO BE ENFORCED WITH INDEX THAT ALSO CHECKS DELETED_AT IS NULL
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ NULL DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS IDX_PROFILES_USER_ID ON PROFILES (USER_ID)
WHERE DELETED_AT IS NULL;
CREATE INDEX IF NOT EXISTS IDX_PROFILES_EMAIL ON PROFILES (EMAIL)
WHERE DELETED_AT IS NULL;
-- for search by email
CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN () RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
CREATE OR REPLACE TRIGGER update_profiles_updated_at BEFORE
UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();