node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "/opt/emqx/data"
}
listeners.tcp.default {
  bind = "0.0.0.0:1883"
  proxy_protocol = true
}
dashboard {
    listeners.http {
        bind = 18083
    }
}
authentication = [ 
  {
    # Device Authentication with JWT tokens
    enable = true
    use_jwks = false
    mechanism = "jwt"
    algorithm = "hmac-based"
    secret = "${DEVICE_TOKEN_SECRET_KEY}"
    secret_base64_encoded = false
    acl_claim_name = "capabilities"
    verify_claims = {
      sub = "${username}"
    }
    disconnect_after_expire = true
    from = "password"
  },
  {
    # User Authentication with basic username/password
    enable = true
    mechanism = "password_based"
    backend = "built_in_database" 
    user_id_type = "username"
    password_hash_algorithm = {
      name = "sha256",
      salt_position = "suffix"
    }
    bootstrap_file = "${EMQX_ETC_DIR}/auth-built-in-db-bootstrap.csv"
    bootstrap_type = "plain"
  }
]