CREATE TYPE OPPERATION_TYPE AS ENUM ('CREATE', 'UPDATE', 'DELETE');

CREATE TABLE IF NOT EXISTS transactions (
    ID UUID PRIMARY KEY default GEN_RANDOM_UUID (),
    DOMAIN_ID UUID NOT NULL,
    INITIATOR_ID UUID NOT NULL,
    OPPERATION_TYPE OPPERATION_TYPE NOT NULL,
    OPPERATION_TARGET VARCHAR(255) NOT NULL,
    TARGET_ID UUID NOT NULL,
    VALUE JSONB, -- can be null because some opperation carry not value other than the initiators and target
    OPPERATION_TIMESTAMP TIMESTAMPTZ NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_DOMAIN_ID ON transactions (DOMAIN_ID, OPPERATION_TIMESTAMP DESC);