CREATE TABLE IF NOT EXISTS USER_ROLES(
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    USER_ID UUID NOT NULL,
    DOMAIN_ID UUID NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ NULL DEFAULT NULL
);

CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN () RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
CREATE OR REPLACE TRIGGER update_user_role_updated_at BEFORE
UPDATE ON user_roles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE UNIQUE INDEX IF NOT EXISTS IDX_USER_ROLE_USER_DOMAIN ON USER_ROLES (USER_ID, DOMAIN_ID)
WHERE DELETED_AT IS NULL;